package com.star;

import java.io.Serializable;

public enum ChatMode implements Serializable {
	START,
	LAST_NAME,
	PHONE_NUMBER,
	GITHUB_EMAIL,
	TEAMS_EMAIL,
	ADDRESS,
	POSTAL_CODE,
	INTERNSHIP_TYPE,
	FINISH_GET_INFO,
	PUBLIC,
	PRIVATE,
	
	EDIT_FIRST_NAME,
	EDIT_LAST_NAME,
	EDIT_PHONE_NUMBER,
	EDIT_GITHUB_EMAIL,
	EDIT_TEAMS_EMAIL,
	EDIT_ADDRESS,
	EDIT_POSTAL_CODE,
	EDIT_INTERNSHIP_TYPE,
}
